name: weatherman
services:
  discord:
    #image: docker.voidwell.com/weatherman/discord
    build:
      context: ./
      dockerfile: Dockerfile.debug
    depends_on:
      - redis
    environment:
      GuildId: "${GUILD_ID}"
      OwnerId: "${OWNER_ID}"
      RedisAddress: "redis:6379"
      DiscordToken: ${DiscordToken}
      DiscordClientId: ${DiscordClientId}
      HereApiKey: "${HERE_API_KEY}"
      PirateWeatherKey: "${PIRATE_WEATHER_KEY}"
      LoggingOutput: "flat"
    volumes:
      - ./src/:/app
      - /data/:/data

  redis:
    image: redis:alpine
    ports: 
      - "6379"