version: '2'
services:
  weatherman.discord:
    environment:
      DiscordToken: ""
      DiscordClientId: ""
      RedisAddress: ""
      HereApiKey: ""
      PirateWeatherKey: ""
    build:
      context: ./
      dockerfile: ./Dockerfile
    volumes:
      - ./data/weatherplugin:/data/
    depends_on: 
      - redis

  redis:
    image: redis:alpine
    ports: 
      - "6379"