name: Publish Docker Image On Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      tag:
        description: "Tag to add to published image"
        required: true
        type: string

permissions:
  contents: read

jobs:
  docker_publish:
    uses: wakeops/ci/.github/workflows/docker-publish.yaml@main
    with:
      image_name: ${{ github.event.repository.name }}
      tag: ${{ inputs.tag || github.event.release.tag_name }}
    secrets: inherit
